---for selecting all colums from actor
select * from actor

----basic select statement

select first_name from actor

select last_name from actor

select first_name,last_name from actor

---SELECT DISTINCT RECORD 
SELECT * FROM FILM

SELECT DISTINCT TITLE FROM FILM

SELECT DISTINCT RENTAL_RATE FROM FILM

SELECT DISTINCT RATING FROM FILM

SELECT DISTINCT FILM_ID FROM FILM

---COUNT
SELECT * FROM FILM
SELECT  COUNT(*) FROM FILM

SELECT COUNT(TITLE) FROM FILM

SELECT COUNT(RATING) FROM FILM

SELECT COUNT(RENTAL_RATE) FROM FILM

-----WHERE
SELECT * FROM FILM

SELECT * FROM FILM WHERE RENTAL_RATE BETWEEN 3 AND 5

SELECT * FROM FILM WHERE RELEASE_YEAR>2005

SELECT * FROM FILM WHERE RATING ='PG-13'

SELECT * FROM FILM WHERE LENGTH >100
---AND
SELECT * FROM FILM WHERE LENGTH >120 AND RATING ='PG-13'
---OR
SELECT * FROM FILM WHERE LENGTH>150 OR RATING='PG-13'
---!
SELECT * FROM FILM WHERE LENGTH!=150 AND RATING='PG-13'

SELECT * FROM FILM WHERE RATING !='PG-13'
----ORDER BY

SELECT * FROM FILM

SELECT * FROM FILM WHERE RATING='PG-13' ORDER BY RATING

SELECT FILM_ID FROM FILM ORDER BY FILM_ID DESC

SELECT * FROM FILM ORDER BY FILM_ID


SELECT * FROM FILM WHERE RATING='PG-13' ORDER BY FILM_ID

SELECT * FROM FILM WHERE RATING='NC-17' ORDER BY FILM_ID ASC,RENTAL_RATE 

----LIMIT
SELECT * FROM FILM LIMIT 5

SELECT * FROM FILM WHERE RATING='NC-17' ORDER BY FILM_ID LIMIT 5

----BETWEEN

SELECT * FROM PAYMENT
SELECT DISTINCT LAST_UPDATE FROM PAYMENT
SELECT DISTINCT PAYMENT_DATE,PAYMENT_ID FROM PAYMENT WHERE PAYMENT_DATE BETWEEN '2007-02-15' AND '2007-02-22'

-----IN
SELECT * FROM FILM WHERE FILM_ID IN(12,16,33,45,89,102)

SELECT * FROM FILM WHERE FILM_ID NOT IN(12,16,33,45,89,102)


SELECT * FROM FILM WHERE RATING IN('PG-13')

SELECT * FROM FILM WHERE REPLACEMENT_COST IN('21.99')

SELECT * FROM FILM WHERE TITLE IN('Beverly Outlaw')

SELECT * FROM FILM WHERE DESCRIPTION IN('A Intrepid Panorama of a Robot And a Boy who must Escape a Sumo Wrestler in Ancient China')
